@startuml design

class Program
{
    DisplayScripture() : void
    QuitOrContinueProgram() : void
    ClearConsole() : void
    RemoveWords() : void
}

class Scripture
{
    -_reference : string
    -_words : List<Word>=new List<Word>
    +Scripture(in reference : string, in scripture : string)
    +GetScripture() : string
    +BlankOutWords() : void
    +AmountOfVisibleWords() : int
    -AmountOfWords() : int
    -GetRandomInt(in maxInt : int, in minInt : int) : int
}

class Word
{
    -_word : string
    -_isBlank : bool
    +Word(in word : string)
    +GetWord() : string
    +MakeBlank() : void
    +IsVisible() : bool
}

class Reference
{
    -_versesNumbers : string
    -_chapterNumber : string
    -_book : string
    +Reference(in reference : string)
    +GetReference() : string
}

Program <|.. Scripture
Scripture <|.. Reference
Scripture <|.. Word

@enduml