@startuml finalDesign

class Program
{
    volumes : List<Scripture>
    books : List<Scripture>
    chapters : List<Scripture>
    verses : List<Scripture>
    commands : List<string>
    SetScriptures() : void
    DisplayInto() : void
    DisplayMenu() : void
    Search(string inquiry) : void
    GetInquiry() : string
    IsACommand(commands : List<string>, potentialCommand : string) : bool
    GetCommand(inquiry : string) : string
    GetSearchingFor(inquiry : string) : string
}

abstract Scripture
{
    -_number : int
    -_name : string
    +Scripture(scriptureCsvLine : string)
    ~SetNumber(number : int) : void
    ~SetName(name : string) : void
    ~SetScripture(csvList : List<string>) : void
    +GetNumber() : int
    +GetName() : string
    ~GetSearchResult() : void
}

class Volume
{
    -_booksNames : List<string>
    +Volume(volumeCsvList : List<string>)
    ~SetNumber(number : int) : void
    ~SetName(name : string) : void
    ~SetScripture(csvList : List<string>) : void
    ~GetSearchResult() : void
}

class Book
{
    -_verseAmountInEachChapter : List<int>
    +Book(bookCsvList : List<string>)
    ~SetNumber(number : int) : void
    ~SetName(name : string) : void
    ~SetScripture(csvList : List<string>) : void
    ~GetSearchResult() : void
}

class Chapter
{
    -_verses : List<string>
    +Chapter(chapterCsvList : List<string>)
    ~SetNumber(number : int) : void
    ~SetName(name : string) : void
    ~SetScripture(csvList : List<string>) : void
    ~GetSearchResult() : void
}

class Verse
{
    -_verse : string
    +Verse(verseCsvList : string)
    ~SetNumber(number : int) : void
    ~SetName(name : string) : void
    ~SetScripture(csvList : List<string>) : void
    ~GetSearchResult() : void
}

@enduml